In [24]:
import numpy as np
import pandas as pd
sample_20220821 = pd.read_csv('./sample_20220821_spark.csv')
sample_20220821.columns

Index(['Unnamed: 0', 'cv_id', 'jd_id', 'tags', 'skills'], dtype='object')

In [27]:
sample_20220821

Unnamed: 0                             cv_id  \
0               0  2c9207157bcb9549017bce3ea49b00fa   
1               1  2c9207157bf91042017c1040330d04d3   
2               2  2c9207157bf91042017c10f871d309f4   
3               3  2c9207157bf91042017c62fce2583411   
4               4  2c9207157bf91042017c6ecc163d3aa8   
...           ...                               ...   
81291       81291  8a69f60582b081f50182b92ebdab1e84   
81292       81292  8a69f61382b080760182b2fb552a0978   
81293       81293  8a69f68b828a2cd901828f891bd10be1   
81294       81294  8a69f68b828a2cd901828fc2ff6a4885   
81295       81295  8a69f68b828a2cd9018291b81ab1557d   

                                  jd_id  \
0      2c9207157bcbb76b017bce3d99ba059a   
1      2c9207157bcbb76b017bec76efca1ca5   
2      2c9207157f347800017f624770866105   
3      2c9207157b9b9199017bca11fd3d3f11   
4      2c9207157bf94d99017c6ecb294930b1   
...                                 ...   
81291  8a69f62f82926a860182a0d7cd7d28bb   
81292  8a69f62f82926a860182af1bf161226d   
81293  8a69c4d6826e58640182804931425820   
81294  8a69c4d6826e5864018285e46d3f17d7   
81295  8a69c4a8820f0ee00182143cd83b2916   

                                              tags  \
0                   ["市场策划","管理","推广","营销","品牌推广"]   
1                 ["销售","团队管理","市场推广","AI","负责管理"]   
2                          ["投资","临床","生物","生物医药"]   
3                ["运营","产品运营","内容运营","美工","互联网产品"]   
4                    ["架构","数字化","管理","云计算","区块链"]   
...                                            ...   
81291                 ["仓储","物流","管理","沟通能力","软件"]   
81292  ["Photoshop","Coredraw","AI","3D工业软件","软件"]   
81293                 ["游戏","动画设计","审核","美术","软件"]   
81294               ["沟通能力","归档","法规","评审","产品开发"]   
81295               ["结构设计","管理","审核","软件","管理工作"]   

                                                  skills  
0      ["Ai","Ar","App","优化","营销","策划","运营","搭建","电商"...  
1                                     ["it规划咨询","云计算咨询"]  
2      ["VC","PPT","SQL","VBA","Kpi","Excel","C/C++",...  
3      ["Vi","Pr","App","Crm","优化","策划","营销","搭建","融资...  
4      ["PPT","Word","Excel","Visio","营销","运营","搭建","...  
...                                                  ...  
81291  O2O,Erp,Wms,Kpi,优化,运营,搭建,驾驶,电商,性能,架构,招投标,施工图,绩...  
81292                        Zcool,电商,优化,搭建,装修,页面设计,平面设计  
81293                   C1,C4D,Icon,舞蹈,美术,项目经理,视频制作,沟通能力  
81294                           制药,内科,配置,策划,美容,团队销售,生物医药  
81295  Top,Bom,优化,电气,仿真,消防,搭建,招聘,电站,迭代,普通话,系统集成,系统测试,...  

[81296 rows x 5 columns]

In [ ]:
def sum_id(series):
    cv_id = series["cv_id"]
    jd_id = series["jd_id"]
    return cv_id + jd_id



In [3]:
sample_20220821['tags']

0                     ["市场策划","管理","推广","营销","品牌推广"]
1                   ["销售","团队管理","市场推广","AI","负责管理"]
2                            ["投资","临床","生物","生物医药"]
3                  ["运营","产品运营","内容运营","美工","互联网产品"]
4                      ["架构","数字化","管理","云计算","区块链"]
                            ...                     
81291                   ["仓储","物流","管理","沟通能力","软件"]
81292    ["Photoshop","Coredraw","AI","3D工业软件","软件"]
81293                   ["游戏","动画设计","审核","美术","软件"]
81294                 ["沟通能力","归档","法规","评审","产品开发"]
81295                 ["结构设计","管理","审核","软件","管理工作"]
Name: tags, Length: 81296, dtype: object

In [27]:
sample_20220821.iloc[222]

Unnamed: 0                                                  222
cv_id                          2c920715802399a801802780282b1c4a
jd_id                          2c920715800e886301801d85fe8c78e6
tags                                                        NaN
skills        ["PPT","Word","Excel","数据分析","沟通能力","财务管理","管理...
Name: 222, dtype: object

In [28]:
sample_20220821.count()

Unnamed: 0    81296
cv_id         81296
jd_id         81296
tags          80589
skills        74527
dtype: int64

In [34]:
sample_20220821.shape

(81296, 5)

In [38]:
sample_20220821[['tags']].dropna()

tags
0                   ["市场策划","管理","推广","营销","品牌推广"]
1                 ["销售","团队管理","市场推广","AI","负责管理"]
2                          ["投资","临床","生物","生物医药"]
3                ["运营","产品运营","内容运营","美工","互联网产品"]
4                    ["架构","数字化","管理","云计算","区块链"]
...                                            ...
81291                 ["仓储","物流","管理","沟通能力","软件"]
81292  ["Photoshop","Coredraw","AI","3D工业软件","软件"]
81293                 ["游戏","动画设计","审核","美术","软件"]
81294               ["沟通能力","归档","法规","评审","产品开发"]
81295               ["结构设计","管理","审核","软件","管理工作"]

[80589 rows x 1 columns]

In [39]:
sample_20220821['tags'].dropna()

0                     ["市场策划","管理","推广","营销","品牌推广"]
1                   ["销售","团队管理","市场推广","AI","负责管理"]
2                            ["投资","临床","生物","生物医药"]
3                  ["运营","产品运营","内容运营","美工","互联网产品"]
4                      ["架构","数字化","管理","云计算","区块链"]
                            ...                     
81291                   ["仓储","物流","管理","沟通能力","软件"]
81292    ["Photoshop","Coredraw","AI","3D工业软件","软件"]
81293                   ["游戏","动画设计","审核","美术","软件"]
81294                 ["沟通能力","归档","法规","评审","产品开发"]
81295                 ["结构设计","管理","审核","软件","管理工作"]
Name: tags, Length: 80589, dtype: object

In [28]:
import numpy as np
import pandas as pd
from zhconv import convert


sample_20220821 = pd.read_csv('./sample_20220821_spark.csv')

# 获取tags列出现的所有的tag
import json
tags_all = []

for line in sample_20220821['tags'].dropna():
    line = json.loads(line)
    tags_all.extend(line)

def map_fun(item):
    # 转中文简体
    item = convert(item, "zh-hans")
    # 转英文小写
    item = item.lower()
    return item

tags_all = list(map(map_fun, tags_all))


with open("./tags_all", "w") as fo:
    for line in tags_all:
        fo.write(line + "\n")

len(tags_all)
#linus 注意:tags_all中的每个tag仍然有分隔符，需要进一步分割。
#linus 可以通过切词避免这种情况么？还是必须指定分隔符分割？

392003

In [15]:
import jieba
sen = "我来到北京清华大学"
sen = "B端大客户销售，5-10亿人民币销售额，海外经验，团队管理。"
seg_list = jieba.cut(sen, cut_all=True)
print("Default Mode: " + "/ ".join(seg_list))  # 全模式

Default Mode: B/ 端/ 大客/ 客户/ 销售/ ，/ 5/ -/ 10/ 亿/ 人民/ 人民币/ 销售/ 销售额/ ，/ 海外/ 外经/ 经验/ ，/ 团队/ 管理/ 。


In [39]:
import jieba
sen = "我来到北京清华大学"
sen = "B端大客户销售，5-10亿人民币销售额，海外经验，团队管理。"
sen = "港澳台/东南亚/欧美区域"
sen = "品牌战略"
sen = "filecoin hello"

seg_list = jieba.lcut(sen, cut_all=False)
print(seg_list)
print("Default Mode: " + "/ ".join(seg_list))  # 精确模式

['filecoin', ' ', 'hello']
Default Mode: filecoin/  / hello


In [36]:
'985'.isdigit()

True

In [42]:
len("  ")

2

In [46]:
"hello,world".split("，,")

['hello,world']

In [51]:
import re
test = "hello,w，orld"
re.split(",|，", test)

['hello', 'w', 'orld']

In [7]:
# encoding=utf-8
import jieba

# jieba.enable_paddle()# 启动paddle模式。 0.40版之后开始支持，早期版本不支持
# strs=["我来到北京清华大学","乒乓球拍卖完了","中国科学技术大学"]
# for str in strs:
#     seg_list = jieba.cut(str,use_paddle=True) # 使用paddle模式
#     print("Paddle Mode: " + '/'.join(list(seg_list)))

seg_list = jieba.cut("我来到北京清华大学", cut_all=True)
print("Full Mode: " + "/ ".join(seg_list))  # 全模式

seg_list = jieba.cut("我来到北京清华大学", cut_all=False)
print("Default Mode: " + "/ ".join(seg_list))  # 精确模式

seg_list = jieba.cut("他来到了网易杭研大厦")  # 默认是精确模式
print(", ".join(seg_list))

seg_list = jieba.cut_for_search("小明硕士毕业于中国科学院计算所，后在日本京都大学深造")  # 搜索引擎模式
print(", ".join(seg_list))

#linus 感觉精确模式比较合适

Building prefix dict from the default dictionary ...
Dumping model to file cache /var/folders/99/wft1658s2mv39cv4wj_rcpqh0000gp/T/jieba.cache
Loading model cost 0.910 seconds.
Prefix dict has been built successfully.


Full Mode: 我/ 来到/ 北京/ 清华/ 清华大学/ 华大/ 大学
Default Mode: 我/ 来到/ 北京/ 清华大学
他, 来到, 了, 网易, 杭研, 大厦
小明, 硕士, 毕业, 于, 中国, 科学, 学院, 科学院, 中国科学院, 计算, 计算所, ，, 后, 在, 日本, 京都, 大学, 日本京都大学, 深造


In [ ]:
# 先对所有的词转中文简体和英文小写
# 还可以添加自定义词典

In [31]:
list_a = [1, 2, 3, 1, 2, 3]
list(set(list_a))

[1, 2, 3]

In [33]:
len("中国")

2

In [34]:
len(9)

TypeError: object of type 'int' has no len()

In [52]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names()
X.toarray()

/Users/jinrirencai/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]])

In [53]:
print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


/Users/jinrirencai/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [63]:
## 中文
corpus_zh = [
    '我喜欢吃苹果',
    '你喜欢吃橘子'
]

import jieba
corpus_zh_out = [' '.join(jieba.cut(s, cut_all=False)) for s in corpus_zh]
corpus_zh_out

['我 喜欢 吃 苹果', '你 喜欢 吃 橘子']

In [64]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus_zh_out)
vectorizer.get_feature_names()
X.toarray()

/Users/jinrirencai/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


array([[1, 0, 1],
       [1, 1, 0]])

In [65]:
vectorizer.get_feature_names()


['喜欢', '橘子', '苹果']

In [67]:
vectorizer = CountVectorizer()
vectorizer

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',


In [95]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["The quick brown fox jumped over the lazy dog."]
text = ["hello", "world"]

#text = open("./dict_col_jieba_filter")
# 创建transform
vectorizer = CountVectorizer()
# 分词并建立词汇表
vectorizer.fit(text)
# 结果输出
(vectorizer.vocabulary_)

{'hello': 0, 'world': 1}

In [110]:
text2 = ["hello word hi"]
text2 = '["Ai","hello","运营","搭建","招聘","架构","法律","客服","国际贸易","绩效考核","项目管理","项目经理","数据分析","证券交易","管理工作","人力资源","战略规划","供应链管理"]'
import jieba
text2 = jieba.lcut(text2, cut_all=False)
text2 = " ".join(text2)
text2 = [text2]
print(text2)
vector = vectorizer.transform(text2)
a = vector.toarray()
a[0]


['[ " Ai " , " hello " , " 运营 " , " 搭建 " , " 招聘 " , " 架构 " , " 法律 " , " 客服 " , " 国际贸易 " , " 绩效考核 " , " 项目管理 " , " 项目经理 " , " 数据分析 " , " 证券交易 " , " 管理工作 " , " 人力资源 " , " 战略规划 " , " 供应链 管理 " ]']


array([1, 0])

In [97]:
sum(a[0])

1

In [79]:
vectorizer.vocabulary_

{'英汉翻译': 2728,
 '资质': 2839,
 '分析化学': 1785,
 '水电工程': 2388,
 'ext': 449,
 'rest': 1141,
 '关系': 1759,
 'vba': 1446,
 'point': 1053,
 '电子电路': 2512,
 '官网': 2007,
 'voip': 1473,
 '存储器': 1997,
 'mcdst': 827,
 'vuex': 1485,
 'hdfs': 571,
 '生物医药': 2493,
 'arttempl': 99,
 '增发': 1973,
 'npm': 936,
 'robotframework': 1158,
 '报告': 2180,
 '白盒': 2532,
 'rfid': 1152,
 '电力': 2503,
 'ui': 1421,
 'jasperreport': 666,
 'mcas': 825,
 '国际金融': 1945,
 'node': 931,
 '节目主持': 2722,
 'directshow': 349,
 'jsonp': 712,
 'springsecurityoauth': 1282,
 'dreamweaver': 371,
 'iconfont': 610,
 '盘点': 2536,
 '文件': 2266,
 '网店': 2673,
 '协议': 1853,
 'glide': 532,
 'pmp': 1050,
 'theano': 1379,
 'ijkplayer': 620,
 'dbms': 327,
 'etl': 437,
 'powerbuilder': 1060,
 'leangoo': 759,
 'cfx': 216,
 'animate': 68,
 'lamp': 748,
 'mac': 800,
 '跨境': 2845,
 'tortoisesvn': 1398,
 '检验': 2370,
 'task': 1359,
 '金蝶': 2908,
 'hr': 583,
 '供冷': 1708,
 '会影': 1690,
 '性能': 2141,
 '园区': 1931,
 '制造': 1802,
 '能够': 2709,
 'zigbee': 1579,
 'cocos2d': 2

In [119]:
def load_dict(dict_path=None):
    dict_col = open(dict_path)
    dict_col = ["hello", "world peace", "mit thu"]
    vectorizer = CountVectorizer()
    # 分词并建立词汇表
    vectorizer.fit(dict_col)
    
    return vectorizer

def gen_vector(vectorizer, text):
    text = jieba.lcut(text, cut_all=False)
    text = sorted(text)
    text = [" ".join(text)]
    print(text)
    vector = vectorizer.transform(text)
    return vector.toarray()[0]

if __name__ == "__main__":
    dict_path = "./dict_col_jieba_filter"
    text = '"thu","HeLlo mit","运营","搭建","招聘","架构","法律","客服"'

    vectorizer = load_dict(dict_path)
    print(vectorizer.vocabulary_)

    vector = gen_vector(vectorizer, text)
    print(vector)

{'hello': 0, 'world': 4, 'peace': 2, 'mit': 1, 'thu': 3}
['    " " " " " " " " " " " " " " " " , , , , , , , HeLlo ii mit thu 客服 招聘 搭建 架构 法律 运营']
[1 1 0 1 0]


In [15]:
import re
text = '"THu","HeLlo mit","运营","搭建","招聘","架构","法律","客服"'
a = re.split("\"|,", text)
a.sort()
"".join(a)

'HeLlo mitTHu客服招聘搭建架构法律运营'

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
# 文件列表
text = ["The quick brown fox jumped over the lazy dog.",
        "The dog.",
        "The fox"]
# 建立transform
vectorizer = TfidfVectorizer()
# 分词，建立词汇表
vectorizer.fit(text)
# 输出结果
print(vectorizer.vocabulary_)
print(vectorizer.idf_)

{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}
[1.69314718 1.28768207 1.28768207 1.69314718 1.69314718 1.69314718
 1.69314718 1.        ]


In [23]:
for word, index in vectorizer.vocabulary_.items():
    print(word, vectorizer.idf_[index])

the 1.0
quick 1.6931471805599454
brown 1.6931471805599454
fox 1.2876820724517808
jumped 1.6931471805599454
over 1.6931471805599454
lazy 1.6931471805599454
dog 1.2876820724517808


In [22]:
# 编码文件
vector = vectorizer.transform(text)
# 输出编码结果
print(vector.shape)
print(vector.toarray())

(3, 8)
[[0.36388646 0.27674503 0.27674503 0.36388646 0.36388646 0.36388646
  0.36388646 0.42983441]
 [0.         0.78980693 0.         0.         0.         0.
  0.         0.61335554]
 [0.         0.         0.78980693 0.         0.         0.
  0.         0.61335554]]
